# Generated by Django 2.2.5 on 2020-12-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20201223_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthqquser',
            old_name='create_time',
            new_name='creat_time',
        ),
    ]
