# Generated by Django 2.2.5 on 2020-12-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goodscategory',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='goodschannel',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='sku',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='skuimage',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='skuspecification',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='specificationoption',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='spu',
            old_name='creat_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='spuspecification',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
